/*REALIZANDO ALTERAÇÕES NA TABELA JÁ CRIADA */
ALTER TABLE [TABELA DE CLIENTES] ALTER COLUMN  [CPF] [CHAR] (11) NOT NULL;
ALTER TABLE [TABELA DE CLIENTES] ADD CONSTRAINT PK_TABELA_CLIENTES PRIMARY KEY CLUSTERED ([CPF]);
