-- SELECIONA TODOS OS DADOS DA TABELA 
SELECT * 
FROM [TABELA DE PRODUTOS];


-- CONSULTANDO UMA UNICA COLUNA
SELECT  [CODIGO DO PRODUTO], [NOME DO PRODUTO]
FROM [TABELA DE PRODUTOS];


--SELECIONANDO DUAS COLUNAS DA TABELA E ORDENANDO A COLUNA DO NOME
SELECT [NOME], [ESTADO] 
FROM [TABELA DE CLIENTES]
ORDER BY [NOME];

--ALTERANDO O NOME DA COLUNA NA NOSSA CONSULTA - UTILIZAMOS O 'AS' E EM SEGUIDA O NOVO NOME DA COLUNA 
SELECT [NOME] AS [NOME DO CLIENTE],  [ESTADO] AS [UF] 
FROM [TABELA DE CLIENTES]
ORDER BY [NOME];

--REMOVENDO VALORES DUPLICADOS
SELECT  DISTINCT [NOME DO PRODUTO]
FROM [TABELA DE PRODUTOS];

--REALIZANDO FILTROS DE CLIENTES QUE REALIZARAM A 1ª COMPRA
SELECT [NOME] AS [NOME DO CLIENTE], ESTADO AS [UF], [PRIMEIRA COMPRA]
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1;


--FILTROS COMPOSTOS  OR - AND
SELECT [NOME], [BAIRRO] 
FROM [TABELA DE CLIENTES]
WHERE [BAIRRO] = 'Copacabana' OR [BAIRRO] = 'Tijuca';

-- OR = UMA OU OUTRA CONDIÇÃO 

SELECT [NOME], [ESTADO], [PRIMEIRA COMPRA] 
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = '1' AND [ESTADO] = 'SP';

--AND  AS DUAS CONDIÇÕES PRECISAM SER ATENDIDAS