-- REALIZANDO ALTERAÇÕES NA TABELA DE ACORDO COM UM FILTRO ESPECIFICO 
--UPDATE = QUAL TABELA SERÁ ALTERADA
--SET = ONDE FAREMOS A ALTERAÇÃO, QUAL COLUNA 


-- APLICAMOS 90% DE DESCONTO NO VALOR DOS PRODUTOS QUE A EMBALAGEM É LATA
UPDATE [TABELA DE PRODUTOS] 
SET [PRECO DE LISTA] = [PRECO DE LISTA] * 0.9
WHERE [EMBALAGEM] = 'Lata';


--NESSE COMANDO REALIZAMOS ALTERAÇÃO NA EMBALAGEM E NO VALOR DE UM PRODUTO DE ACORDO COM O FILTRO DO CODIGO DO PRODUTO
UPDATE [TABELA DE PRODUTOS] 
SET [EMBALAGEM] = 'Garrafa', [PRECO DE LISTA] = 8.10
WHERE [CODIGO DO PRODUTO] = '1088126';