-- DELETANDO PRODUTOS DE ACORDO COM O CODIGO 
-- ATENÇÃO, SE REALIZAR O COMANDO DELETE SEM UMA CONDIÇÃO, TODO O BANCO DE DADOS SERÁ APAGADO 

DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1004327';