/*CRIANDO O BANCO DE DADOS */
CREATE DATABASE SUCOS_VENDAS

/*CRIANDO A TABELA CLIENTES */
CREATE TABLE [TABELA DE CLIENTES]( 
[CPF] [CHAR] (11),
[NOME] [VARCHAR]  (150),
[RUA] [VARCHAR]  (150),
[COMPLEMENTO] [VARCHAR]  (150),
[BAIRRO] [VARCHAR]  (150),
[ESTADO] [CHAR]  (2),
[CEP] [CHAR]  (8),
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [CHAR]  (1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME MINIMO] [FLOAT],
[PRIMEIRA COMPRA] [BIT]
);

